// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NghiemThiVanAnh078.Data;

#nullable disable

namespace NghiemThiVanAnh078.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240106065517_Create_table_NTVA078")]
    partial class Create_table_NTVA078
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("NghiemThiVanAnh078.Models.NTVA078", b =>
                {
                    b.Property<string>("Masinhvien")
                        .HasColumnType("TEXT");

                    b.Property<double>("Diem")
                        .HasColumnType("REAL");

                    b.Property<int>("Tuoi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Masinhvien");

                    b.ToTable("NTVA078");
                });
#pragma warning restore 612, 618
        }
    }
}
